### ISSUE TITLE
Bad blog post truncation with Chinese text

### ISSUE THREAD

**Issue by lucasholder** [vim-labs/gatsby-theme-sky-lite#5]
See https://github.com/gatsbyjs/gatsby/issues/22390 .. I'm posting it here too in case this is actually a problem with the theme.

**Comment by iRyanBell** [comment]
> See [gatsbyjs/gatsby#22390](https://github.com/gatsbyjs/gatsby/issues/22390) .. I'm posting it here too in case this is actually a problem with the theme.

Good catch. At first glance, it looks like this is deep in the mdx plugin.
