### ISSUE TITLE
Flash Of Unstyled Content (FOUC)

### ISSUE THREAD

**Issue by lucasholder** [vim-labs/gatsby-theme-sky-lite#6]
When loading the page with `gatsby build; gatsby serve;`, the content gets loaded unstyled (or only partially styled) and suddenly gets styled after the JavaScript loads, causing an annoying "flicker":

![fouc](https://user-images.githubusercontent.com/62086489/77028579-86ad1d80-696f-11ea-9b36-97d3a65ada4e.gif)

Probably related: https://github.com/gatsbyjs/gatsby/issues/15097

**Comment by lucasholder** [comment]
After further investigation, it might be due to the Roboto font causing the flicker once it loads.. Not sure thought. Gonna keep investigating.

**Comment by lucasholder** [comment]
Apparently the font loader plugin this is using is deprecated: https://github.com/escaladesports/legacy-gatsby-plugin-web-font-loader

**Comment by lucasholder** [comment]
I solved the issue by using a different font loader plugin:

```js
    {
      resolve: "gatsby-plugin-prefetch-google-fonts",
      options: {
        fonts: [
          {
            family: "Roboto"
          },
          {
            family: "Work Sans",
            variants: ["800"]
          }
        ]
      }
    }
```

**Comment by iRyanBell** [comment]
Very nice! I'll merge that change into the repo. Do you want to add a PR?
