### ISSUE TITLE
List of possible overrides

### ISSUE THREAD

**Issue by mtliendo** [vim-labs/gatsby-theme-sky-lite#7]
This starter is so nice!

Just curious is there is a way to override a few of the items?  

For example, the title on the banner and the navigation title are both tied to the site metadata title. Is there a way to split those up?

Also, the color banner and the purple buttons used, can those be overridden?

Just curious is this was achievable, any insight would be super helpful, thanks again for taking the time to create this!

**Comment by iRyanBell** [comment]
Hey, thanks! You can use a `/src/gatsby-theme-sky-lite` directory to run any overrides to the theme, which will be called in place of the defaults. This theme uses a MaterialUI @ https://github.com/vim-labs/gatsby-theme-sky-lite/blob/master/src/style/theme.js.

I've added an example for this now in v1.3.2: https://github.com/vim-labs/gatsby-theme-sky-lite-starter/tree/master/src/gatsby-theme-sky-lite/style

<img width="1091" alt="Now available in rebeccapurple" src="https://user-images.githubusercontent.com/25379378/77683736-177a8f00-6f56-11ea-83d2-e3b1b9bb1df7.png">

**Comment by mtliendo** [comment]
Too ez! Thanks so much!
