### ISSUE TITLE
Read more button after clicking View All on a tag returns 404 page

### ISSUE THREAD

**Issue by py563** [vim-labs/gatsby-theme-sky-lite#9]
Steps: 
- on starter website open a blog post
- click on a tag for the post, which opens posts for that tag
- click on view all at bottom and then click on read more
- it returns 404 page

![error-sky-lite-starter](https://user-images.githubusercontent.com/6139284/83322436-50482480-a275-11ea-83f8-fab2b2d6b6af.gif)

**Comment by iRyanBell** [comment]
Thank you for your detailed description of the issue -- Beautiful bug report! This has been patched in the latest version (1.4.1) on npm.
